import { Category, Product, SiteSettings } from '../types';

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  storeName: 'Anu Atelier',
  tagline: 'Handmade with love, rooted in tradition',
  whatsappNumber: '9555562542',
  supportEmail: 'anushka32199@gmail.com',
  freeDeliveryThreshold: 100, // Explicitly specified: Free delivery above ₹100
  standardDeliveryFee: 40,
  announcementText: '✨ FREE Delivery on all orders above ₹100 | Handcrafted by Indian Artisans 🌸',
  codAvailable: true,
  replacementDays: 15,
};

export const CATEGORIES: Category[] = [
  {
    id: 'terracotta-clay',
    slug: 'terracotta-clay',
    name: 'Terracotta & Clay Items',
    description: 'Earthy, eco-friendly terracotta pottery, diyas, hand-carved tableware and figurines.',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { id: 'pots', name: 'Pots & Planters' },
      { id: 'diyas', name: 'Diyas' },
      { id: 'jewelry', name: 'Clay Jewelry' },
      { id: 'cookware', name: 'Cookware' },
      { id: 'figurines', name: 'Figurines' },
      { id: 'tableware', name: 'Tableware' },
      { id: 'wind-chimes', name: 'Wind Chimes' },
      { id: 'vases', name: 'Vases' },
    ],
  },
  {
    id: 'embroidered-clothes',
    slug: 'embroidered-clothes',
    name: 'Embroidered & Hand-Stitched',
    description: 'Exquisite needlework, traditional Chikankari, Kantha, and Sashiko garments for women.',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { id: 'kurtis', name: 'Kurtis' },
      { id: 'dupattas', name: 'Dupattas' },
      { id: 'sarees', name: 'Sarees' },
      { id: 'jackets', name: 'Jackets' },
      { id: 'scarves', name: 'Scarves & Stoles' },
      { id: 'quilts', name: 'Quilts' },
      { id: 'blouses', name: 'Blouses' },
      { id: 'frocks', name: 'Frocks' },
    ],
  },
  {
    id: 'other-handicrafts',
    slug: 'other-handicrafts',
    name: 'Other Handicrafts',
    description: 'Jute bags, macrame wall hangings, wooden toys, bamboo baskets, and folk art.',
    image: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { id: 'jute-bags', name: 'Jute Bags' },
      { id: 'macrame-hangings', name: 'Macrame Hangings' },
      { id: 'wooden-toys', name: 'Wooden Toys' },
      { id: 'bamboo-baskets', name: 'Bamboo Baskets' },
      { id: 'brass-idols', name: 'Brass Idols' },
      { id: 'rugs', name: 'Rugs & Dhurries' },
    ],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    slug: 'cute-girl-hand-stitching-clothes',
    name: 'A Cute Little Girl Hand Stitching Clothes',
    description: 'A delicate handcrafted textile artwork showcasing authentic hand-stitched folk artistry. Made with pure cotton threads on handloom khadi fabric.',
    price: 499,
    originalPrice: 699,
    categoryId: 'embroidered-clothes',
    categoryName: 'Embroidered & Hand-Stitched',
    subcategoryId: 'kurtis',
    subcategoryName: 'Kurtis',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsTRyROcOR6uyNs9Z5Fv9-eyIYdjHtCNrlk7vHaWakRRXWnhhuZsEWsUE&s=10',
    stock: 10,
    status: 'published',
    badge: 'Bestseller',
    rating: 4.8,
    reviewsCount: 14,
    soldCount: 42,
    highlights: ['100% Hand-embroidered', 'Pure Khadi Cotton', 'Wash with gentle care', 'Artisan made in Varanasi'],
    specs: { Material: 'Pure Cotton', Technique: 'Hand Stitch', Origin: 'Uttar Pradesh, India', Dimensions: '30cm x 40cm' },
    createdAt: 1790342440684,
  },
  {
    id: 'prod_2',
    slug: 'colorful-applique-pouch',
    name: 'Colorful Applique Pouch',
    description: 'A vibrant handmade applique utility pouch with durable jute lining and brass zip. Perfect for cosmetics, stationeries, and travel essentials.',
    price: 799,
    originalPrice: 999,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'jute-bags',
    subcategoryName: 'Jute Bags',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpijLGyKIV-d9VrEGbWzLLHe44J1P3BFvgHJq4E9d7gA&s=10',
    stock: 15,
    status: 'published',
    badge: 'New',
    rating: 4.9,
    reviewsCount: 8,
    soldCount: 29,
    highlights: ['Natural Golden Jute', 'Hand-cut Applique Work', 'Antique Brass Zipper', 'Eco-friendly'],
    specs: { Material: 'Jute & Cotton', Closure: 'Zip', Dimensions: '22cm x 15cm', Weight: '120g' },
    createdAt: 1790342450684,
  },
  {
    id: 'prod_3',
    slug: 'sashiko-embroidered-jeans',
    name: 'Sashiko Embroidered Jeans',
    description: 'Upcycled vintage denim reimagined with intricate Japanese Sashiko hand-stitching and Indian geometric motifs. Each piece is unique.',
    price: 2499,
    originalPrice: 3299,
    categoryId: 'embroidered-clothes',
    categoryName: 'Embroidered & Hand-Stitched',
    subcategoryId: 'jackets',
    subcategoryName: 'Jackets',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHAZqy4uNX9_yihi4CXgNAhsSr7c9Q4f6MovYgs9Xe8A&s=10',
    stock: 5,
    status: 'published',
    badge: 'Limited',
    rating: 5.0,
    reviewsCount: 6,
    soldCount: 15,
    highlights: ['One of a kind', 'Hand-stitched over 18 hours', 'Premium heavy cotton denim', 'Reinforced seams'],
    specs: { Material: '100% Cotton Denim', Fit: 'Relaxed Straight', Care: 'Gentle hand wash inside out' },
    createdAt: 1790342460684,
  },
  {
    id: 'prod_4',
    slug: 'floral-fairy-light-hoop',
    name: 'Floral Fairy Light Hoop',
    description: 'A glowing floral fairy light embroidery hoop crafted with preserved botanicals and warm micro-LED lights. Creates a dreamy bedside ambience.',
    price: 1299,
    originalPrice: 1599,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'macrame-hangings',
    subcategoryName: 'Macrame Hangings',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4_rZRO56o2R8ll_Fy1qnzC7fXqMm_IjfT0W_0IV1OdQ&s=10',
    stock: 8,
    status: 'published',
    badge: 'Bestseller',
    rating: 4.7,
    reviewsCount: 19,
    soldCount: 53,
    highlights: ['Warm White LEDs included', 'Natural Beechwood Hoop', 'Battery powered (AA)', 'Lightweight'],
    specs: { Diameter: '25cm', Power: '2x AA Batteries (included)', Material: 'Wood & Chiffon' },
    createdAt: 1790342470684,
  },
  {
    id: 'prod_5',
    slug: 'bright-yarn-flower-hanging',
    name: 'Bright Yarn Flower Hanging',
    description: 'Vibrant punch-needle yarn wall hanging depicting blooming floral meadows. Adds a splash of warmth and handmade cheer to any wall.',
    price: 999,
    originalPrice: 1299,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'macrame-hangings',
    subcategoryName: 'Macrame Hangings',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXr2u7o7lkBiPl-MEsNkGFGgLCDdQh0nF3o9S0PB3izA&s=10',
    stock: 12,
    status: 'published',
    badge: 'Handmade',
    rating: 4.6,
    reviewsCount: 11,
    soldCount: 34,
    highlights: ['Soft Wool Blend Yarn', 'Hanging Cord attached', 'Boho nursery & bedroom decor'],
    specs: { Dimensions: '20cm x 35cm', Technique: 'Punch Needle Art', Weight: '200g' },
    createdAt: 1790342480684,
  },
  {
    id: 'prod_6',
    slug: 'tiny-woven-daisy-basket',
    name: 'Tiny Woven Daisy Basket',
    description: 'Miniature bamboo basket tightly woven by master bamboo weavers, adorned with hand-crocheted daisy blossoms. Perfect for trinkets and gifting.',
    price: 599,
    originalPrice: 799,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'bamboo-baskets',
    subcategoryName: 'Bamboo Baskets',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmvGxiNqCibZWaa070PMZ3JZGA3Fr4lz68cAi_iWoE0A&s=10',
    stock: 20,
    status: 'published',
    badge: 'New',
    rating: 4.9,
    reviewsCount: 15,
    soldCount: 62,
    highlights: ['Natural Assam Bamboo', 'Chemical-free polish', 'Hand crocheted daisy trim'],
    specs: { Material: 'Bamboo Cane', Diameter: '14cm', Height: '10cm' },
    createdAt: 1790342490684,
  },
  {
    id: 'prod_7',
    slug: 'floral-embroidered-beanie',
    name: 'Floral Embroidered Beanie',
    description: 'Warm ribbed winter beanie hand-stitched with meadow wildflowers using fine silk threads. Keeps you cozy with a touch of elegance.',
    price: 699,
    originalPrice: 899,
    categoryId: 'embroidered-clothes',
    categoryName: 'Embroidered & Hand-Stitched',
    subcategoryId: 'scarves',
    subcategoryName: 'Scarves',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdN7QGCSpJx-JLAZtb2LMZLi68He6hI_iyjX3yxROCfA&s=10',
    stock: 25,
    status: 'published',
    badge: null,
    rating: 4.8,
    reviewsCount: 7,
    soldCount: 28,
    highlights: ['Ultra-soft acrylic & wool blend', 'One size fits all stretch', 'Hand-stitched floral crest'],
    specs: { Fabric: 'Wool Knit', Care: 'Hand wash cold' },
    createdAt: 1790342500684,
  },
  {
    id: 'prod_8',
    slug: 'hand-stitched-fabric-motifs',
    name: 'Hand-stitched Fabric Motifs (Pack of 3)',
    description: 'Decorative set of handcrafted fabric applique motifs. Can be ironed or stitched onto totes, jackets, shirts, or cushions.',
    price: 349,
    originalPrice: 499,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'jute-bags',
    subcategoryName: 'Jute Bags',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1_b2ZJsjCwOH9gJ1RFzYFCb0VxNj8YOmGjeJD2y1v0A&s=10',
    stock: 30,
    status: 'published',
    badge: null,
    rating: 4.7,
    reviewsCount: 12,
    soldCount: 88,
    highlights: ['Pack of 3 unique designs', 'Ready-to-stitch edge', 'Colorfast embroidery'],
    specs: { PackSize: '3 Pieces', Dimensions: '7cm each' },
    createdAt: 1790342510684,
  },
  {
    id: 'prod_9',
    slug: 'patchwork-boro-pillow',
    name: 'Patchwork Boro Pillow Cover',
    description: 'Artisanal indigo cushion cover created from salvaged handloom swatches using traditional Indian Kantha quilting and Japanese Boro philosophy.',
    price: 1499,
    originalPrice: 1899,
    categoryId: 'other-handicrafts',
    categoryName: 'Other Handicrafts',
    subcategoryId: 'rugs',
    subcategoryName: 'Rugs',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFDLuh12PswfHbASigaUtRXLglqQKclRBX2lL_2C_GHA&s=10',
    stock: 7,
    status: 'published',
    badge: 'Handmade',
    rating: 4.9,
    reviewsCount: 9,
    soldCount: 22,
    highlights: ['Upcycled handloom textiles', 'Hidden zipper closure', 'Pre-washed softness'],
    specs: { Dimensions: '45cm x 45cm (18x18 inch)', Insert: 'Not included', Material: '100% Handloom Cotton' },
    createdAt: 1790342520684,
  },
];
