import { ReelStory } from '../types';

export const INITIAL_REELS: ReelStory[] = [
  // --- 8 COMPLETELY DISTINCT ARTISAN VIDEOS (ZERO REPETITION) WITH 100% PURE INSTRUMENTAL MUSIC ---
  {
    id: 'reel_artisan_pottery_wheel',
    type: 'artisan',
    title: 'Master Woman Potter Shaping Earthenware on Spinning Wheel',
    authorName: 'Anupama Sharma',
    authorRole: 'Master Ceramic Sculptor',
    authorAvatar: '/img/story-clay-prep.jpg',
    location: 'Gorakhpur, Uttar Pradesh',
    mediaType: 'video',
    mediaUrl: '/videos/reel-pottery-molding.mp4',
    caption: 'Watch master artisan Anupama shaping wet terracotta clay directly on the spinning wheel. Hand-turned with generational grace, completely natural, and sun-baked before entering the traditional kiln.',
    likesCount: 16840,
    viewsCount: '480k',
    badge: '🎥 Live Pottery Making',
    musicTrack: {
      title: 'Vadodara Sitar & Percussion (Instrumental) 🪕',
      artist: 'Kevin MacLeod (Pure Sitar Instrumental - No Vocals)',
      audioUrl: '/audio/vadodora-sitar.mp3',
    },
    craftTag: {
      productId: 'prod_3',
      productSlug: 'handcrafted-terracotta-chai-kulhad-set',
      productName: 'Handcrafted Terracotta Chai Kulhad Set (Pack of 6)',
      productPrice: 399,
      productImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
  },
  {
    id: 'reel_artisan_baby_krishna',
    type: 'artisan',
    title: 'Artisan Hand-Painting Fine Ceramic Vases with Natural Pigments',
    authorName: 'Sunita Devi',
    authorRole: 'Ceramic Art & Painting',
    authorAvatar: '/img/baby-ganesha-clay-art.jpg',
    location: 'Varanasi, Uttar Pradesh',
    mediaType: 'video',
    mediaUrl: '/videos/reel-ceramic-modeling.mp4',
    caption: 'Sunita meticulously hand-paints intricate cobalt blue floral motifs on ceramic vessels using delicate sable brushes. Every stroke is applied freehand without stencils or machine printing.',
    likesCount: 19420,
    viewsCount: '520k',
    badge: '🎥 Ceramic Painting Video',
    musicTrack: {
      title: 'Shri Nilotpala Divine Veena (Instrumental) 🪕',
      artist: 'L. Ramakrishnan (Pure Classical Veena - No Vocals)',
      audioUrl: '/audio/veena-melody.ogg',
    },
    craftTag: {
      productId: 'prod_13',
      productSlug: 'artisanal-air-dry-foam-clay-baby-ganesha-ji',
      productName: 'Artisanal Air-Dry Foam Clay Baby Ganesha Ji',
      productPrice: 349,
      productImage: '/img/baby-ganesha-clay-art.jpg',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'reel_artisan_chikankari',
    type: 'artisan',
    title: 'Master Woman Artisan Hand-Crocheting & Needle-Weaving Heirloom Threads',
    authorName: 'Shabana Begum',
    authorRole: 'Master Needlework Artisan',
    authorAvatar: '/img/reel-chikankari-embroidery.jpg',
    location: 'Lucknow, Uttar Pradesh',
    mediaType: 'video',
    mediaUrl: '/videos/reel-embroidery-needlework.mp4',
    caption: 'Shabana Begum delicately loops organic yarn with hand-held crochet needles. Over 10,000 passes create our signature breathable heirloom textiles, celebrating generational feminine empowerment.',
    likesCount: 18100,
    viewsCount: '580k',
    badge: '🎥 Hand Needlework Video',
    musicTrack: {
      title: 'Jalandhar Bansuri Flute & Sitar Raag (Instrumental) 🪈',
      artist: 'Kevin MacLeod (Pure Sitar & Flute - No Vocals)',
      audioUrl: '/audio/jalandhar-rag.mp3',
    },
    craftTag: {
      productId: 'prod_7',
      productSlug: 'hand-embroidered-chikankari-cotton-kurti',
      productName: 'Hand-Embroidered Chikankari Pure Cotton Kurti',
      productPrice: 1899,
      productImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'reel_artisan_nursery_mural',
    type: 'artisan',
    title: 'Artist Aditi Hand-Painting Custom Wall Mural Artwork on Canvas',
    authorName: 'Aditi & Vikram Verma',
    authorRole: 'In-Home Muralists',
    authorAvatar: '/img/reel-mural-painting.jpg',
    location: 'Noida & Lucknow, India',
    mediaType: 'video',
    mediaUrl: '/videos/reel-artist-painting.mp4',
    caption: 'Aditi paints delicate leaves, feathers, and whimsical character smiles stroke by stroke with child-safe eco acrylics. Zero decals, zero factory stickers — pure soulful art for your room.',
    likesCount: 24900,
    viewsCount: '740k',
    badge: '🎥 Fine Art Mural Video',
    musicTrack: {
      title: 'Raag Kiravani Classical Violin Solo (Instrumental) 🎻',
      artist: 'L. Ramakrishnan (Pure Indian Classical Violin - No Vocals)',
      audioUrl: '/audio/kiravani-violin.ogg',
    },
    craftTag: {
      productId: 'prod_12',
      productSlug: 'penguin-lamp-post-custom-wall-mural',
      productName: 'Whimsical Hand-Painted Penguin Lamp Post Custom Wall Mural Service',
      productPrice: 499,
      productImage: '/img/penguin-lamp-post-wall-mural.jpg',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 36,
  },

  // --- COLLABORATIVE ARTISAN & CRAFT SHOWCASE REELS (DISTINCT CRAFTS) ---
  {
    id: 'reel_customer_1',
    type: 'customer',
    title: 'Master Craftsman Hand-Tooling & Burnishing Heirloom Leather Art',
    authorName: 'Rohan Malhotra',
    authorRole: 'Leather Artisan',
    authorAvatar: '/img/penguin-lamp-post-wall-mural.jpg',
    location: 'South Delhi, India',
    mediaType: 'video',
    mediaUrl: '/videos/reel-leather-crafting.mp4',
    caption: 'Rohan carefully bevels, carves, and burnishes vegetable-tanned leather by hand using traditional bone folders and awls. Handcrafted to develop a deep patina that lasts for generations.',
    likesCount: 14200,
    viewsCount: '390k',
    badge: '🎥 Leather Handcraft Video',
    musicTrack: {
      title: 'Eastern Thought Sitar & Tanpura Symphony (Instrumental) 🎶',
      artist: 'Kevin MacLeod (Pure Sitar Meditation - No Vocals)',
      audioUrl: '/audio/eastern-thought.mp3',
    },
    craftTag: {
      productId: 'prod_12',
      productSlug: 'penguin-lamp-post-custom-wall-mural',
      productName: 'Whimsical Hand-Painted Penguin Lamp Post Custom Wall Mural Service',
      productPrice: 499,
      productImage: '/img/penguin-lamp-post-wall-mural.jpg',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
  },
  {
    id: 'reel_customer_2',
    type: 'customer',
    title: 'Artisan Hand-Shaping Molten Glass Figurine with Traditional Tools',
    authorName: 'Devendra & Studio Artisans',
    authorRole: 'Flame Glass Artists',
    authorAvatar: '/img/Clay Baby Krishna with Flute and Pot.png',
    location: 'Firozabad, Uttar Pradesh',
    mediaType: 'video',
    mediaUrl: '/videos/reel-glass-crafting.mp4',
    caption: 'Devendra shaping glowing molten glass over high-heat torches into intricate artisanal figurines. Generational mastery of temperature, gravity, and manual precision.',
    likesCount: 12500,
    viewsCount: '310k',
    badge: '🎥 Glass Artisans Video',
    musicTrack: {
      title: 'Jalandhar Bansuri Flute & Sitar Raag (Instrumental) 🪈',
      artist: 'Kevin MacLeod (Pure Sitar & Flute - No Vocals)',
      audioUrl: '/audio/jalandhar-rag.mp3',
    },
    craftTag: {
      productId: 'prod_14',
      productSlug: 'artisanal-air-dry-foam-clay-baby-krishna-ji',
      productName: 'Artisanal Air-Dry Foam Clay Baby Krishna Ji with Bansuri & Butter Pot',
      productPrice: 349,
      productImage: '/img/Clay Baby Krishna with Flute and Pot.png',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 60,
  },
  {
    id: 'reel_customer_3',
    type: 'customer',
    title: 'Heritage Weaver Operating Wooden Handloom Shuttle on Pure Cotton',
    authorName: 'Simran & Harpreet',
    authorRole: 'Handloom Connoisseurs',
    authorAvatar: '/img/artisanal-friendship-handkerchief.jpg',
    location: 'Chandigarh, Punjab',
    mediaType: 'video',
    mediaUrl: '/videos/reel-handloom-stitching.mp4',
    caption: 'Watching the rhythmic dance of the shuttle across organic khadi cotton on a traditional wooden loom. The seam finishes and natural textures are a testament to true artisanal dedication.',
    likesCount: 11400,
    viewsCount: '290k',
    badge: '🎥 Handloom Weaving Reel',
    musicTrack: {
      title: 'Vadodara Sitar & Percussion (Instrumental) 🪕',
      artist: 'Kevin MacLeod (Pure Sitar Instrumental - No Vocals)',
      audioUrl: '/audio/vadodora-sitar.mp3',
    },
    craftTag: {
      productId: 'prod_10',
      productSlug: 'artisanal-friendship-heirloom-handkerchief-customizable',
      productName: 'Artisanal Friendship Heirloom Handkerchief (Customizable)',
      productPrice: 199,
      productImage: '/img/artisanal-friendship-handkerchief.jpg',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 72,
  },
  {
    id: 'reel_customer_4',
    type: 'customer',
    title: 'Master Sculptor Delicately Carving Traditional Clay Model Figurine',
    authorName: 'Amitabh & Sangeeta',
    authorRole: 'Heritage Clay Sculptors',
    authorAvatar: '/img/shri-radhe-handcrafted-card.jpg',
    location: 'Jaipur, Rajasthan',
    mediaType: 'video',
    mediaUrl: '/videos/reel-fabric-tailoring.mp4',
    caption: 'Master sculptor refining facial contours, ornaments, and sacred motifs on handcrafted clay figurines. Every stroke is guided by generational intuition, patience, and artistic passion.',
    likesCount: 9800,
    viewsCount: '240k',
    badge: '🎥 Master Sculptor Video',
    musicTrack: {
      title: 'Shri Nilotpala Divine Veena (Instrumental) 🪕',
      artist: 'L. Ramakrishnan (Pure Classical Veena - No Vocals)',
      audioUrl: '/audio/veena-melody.ogg',
    },
    craftTag: {
      productId: 'prod_11',
      productSlug: 'handcrafted-shri-radhe-devotional-card',
      productName: 'Handcrafted Shri Radhe Devotional Greeting Card & Keepsake',
      productPrice: 249,
      productImage: '/img/shri-radhe-handcrafted-card.jpg',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 84,
  },
];
